services:
  frontend:
    container_name: jantools-v2
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    command: sh -c "yarn install && yarn dev --host"
    volumes:
      - .:/app
    ports:
      - "5173:5173"