version: '3.9'
services:
  frontend:
    container_name: jantools-v2
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    ports:
      - "5173:5173"